### ISSUE TITLE
Rack raise an error >Rack::Lint::LintError: env missing required key SERVER_NAME

### ISSUE THREAD

**Issue by 23prime** [23prime/gokabot#57]
Following errors are occurred from 2020-02-10, with span of a few hours.

```
Rack::Lint::LintError: env missing required key SERVER_NAME
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/lint.rb:21:in `assert'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/lint.rb:279:in `block in check_env'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/lint.rb:278:in `each'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/lint.rb:278:in `check_env'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/lint.rb:44:in `_call'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/lint.rb:38:in `call'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/show_exceptions.rb:23:in `call'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/common_logger.rb:38:in `call'
	/usr/local/bundle/ruby/2.6.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:231:in `call'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/content_length.rb:17:in `call'
	/usr/local/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'
	/usr/local/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
	/usr/local/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
	/usr/local/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
```

## Informations

- Previous build on Jenkins: [#5](http://18.177.115.213/jenkins/job/gokabot-line/6/) or [#6](http://18.177.115.213/jenkins/job/gokabot-line/6/)
- Previous push (commit ID): 9f3a994 or 8277ae3

**Comment by 23prime** [comment]
Resolved by ce56421
